<!DOCTYPE html>
<head>
 <meta charset="utf-8">
 <?php echo $this->headTitle()?>
 <meta name="description" content="<?php echo $this->description?>">
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
 <link rel="stylesheet" type="text/css"
     href="<?php echo $this->baseUrl('css/base.css'); ?>" />
</head>
<body>
<div class="container">

<?=$this->layout()->content?>

</div><!-- /container -->
</body>
</html>